import { defineObject, FieldType } from 'twenty-sdk/define';
import {
  CLAIM_OBJECT_UNIVERSAL_IDENTIFIER,
  CLAIM_CLAIM_NUMBER_FIELD_UNIVERSAL_IDENTIFIER,
} from '../constants/universal-identifiers';

export const CLAIM_OBJECT_ID = CLAIM_OBJECT_UNIVERSAL_IDENTIFIER;
export const CLAIM_NAME_FIELD_ID = CLAIM_CLAIM_NUMBER_FIELD_UNIVERSAL_IDENTIFIER;


export default defineObject({
  universalIdentifier: CLAIM_OBJECT_ID,
  nameSingular: 'claim',
  namePlural: 'claims',
  labelSingular: 'Claim',
  labelPlural: 'Claims',
  description: 'Claim record',
  icon: 'IconFileAlert',
  labelIdentifierFieldMetadataUniversalIdentifier: CLAIM_NAME_FIELD_ID,
  fields: [
    {
      universalIdentifier: CLAIM_NAME_FIELD_ID,
      type: FieldType.TEXT,
      name: 'claimNumber',
      label: 'Claim Number',
      description: 'Claim Number',
      icon: 'IconHash',
      isLabelIdentifier: true,
    },
    {
      universalIdentifier: '4a7c1b5e-2f8d-4e9a-8b1c-7d9a3f2b1e0c',
      type: FieldType.SELECT,
      name: 'claimType',
      label: 'Claim Type',
      description: 'Claim Type',
      icon: 'IconCategory',
      options: [
        { id: '4a7c1b5e-2f8d-4e9a-8b1c-7d9a3f2b1e01', value: 'DEATH', label: 'Death', color: 'gray', position: 0 },
        { id: '4a7c1b5e-2f8d-4e9a-8b1c-7d9a3f2b1e02', value: 'MATURITY', label: 'Maturity', color: 'green', position: 1 },
        { id: '4a7c1b5e-2f8d-4e9a-8b1c-7d9a3f2b1e03', value: 'HEALTH', label: 'Health', color: 'blue', position: 2 },
        { id: '4a7c1b5e-2f8d-4e9a-8b1c-7d9a3f2b1e04', value: 'MOTOR_OD', label: 'Motor OD', color: 'orange', position: 3 },
        { id: '4a7c1b5e-2f8d-4e9a-8b1c-7d9a3f2b1e05', value: 'MOTOR_TP', label: 'Motor TP', color: 'orange', position: 4 },
        { id: '4a7c1b5e-2f8d-4e9a-8b1c-7d9a3f2b1e06', value: 'FIRE', label: 'Fire', color: 'red', position: 5 },
        { id: '4a7c1b5e-2f8d-4e9a-8b1c-7d9a3f2b1e07', value: 'TRAVEL', label: 'Travel', color: 'sky', position: 6 },
        { id: '4a7c1b5e-2f8d-4e9a-8b1c-7d9a3f2b1e08', value: 'PA', label: 'Personal Accident', color: 'purple', position: 7 },
        { id: '4a7c1b5e-2f8d-4e9a-8b1c-7d9a3f2b1e09', value: 'CRITICAL_ILLNESS', label: 'Critical Illness', color: 'red', position: 8 },
      ]
    },
    {
      universalIdentifier: '4a7c1b5e-2f8d-4e9a-8b1c-7d9a3f2b1e0d',
      type: FieldType.DATE_TIME,
      name: 'incidentDate',
      label: 'Incident Date',
      description: 'Incident Date',
      icon: 'IconCalendar',
    },
    {
      universalIdentifier: '4a7c1b5e-2f8d-4e9a-8b1c-7d9a3f2b1e0e',
      type: FieldType.DATE_TIME,
      name: 'intimationDate',
      label: 'Intimation Date',
      description: 'Intimation Date',
      icon: 'IconCalendar',
    },
    {
      universalIdentifier: '4a7c1b5e-2f8d-4e9a-8b1c-7d9a3f2b1e0f',
      type: FieldType.CURRENCY,
      name: 'claimAmount',
      label: 'Claim Amount',
      description: 'Claim Amount',
      icon: 'IconCurrencyDollar',
    },
    {
      universalIdentifier: '4a7c1b5e-2f8d-4e9a-8b1c-7d9a3f2b1e10',
      type: FieldType.CURRENCY,
      name: 'settledAmount',
      label: 'Settled Amount',
      description: 'Settled Amount',
      icon: 'IconCurrencyDollar',
    },
    {
      universalIdentifier: '4a7c1b5e-2f8d-4e9a-8b1c-7d9a3f2b1e11',
      type: FieldType.SELECT,
      name: 'status',
      label: 'Status',
      description: 'Status',
      icon: 'IconStatusChange',
      defaultValue: "'INTIMATED'",
      options: [
        { id: '4a7c1b5e-2f8d-4e9a-8b1c-7d9a3f2b1e1a', value: 'INTIMATED', label: 'Intimated', color: 'gray', position: 0 },
        { id: '4a7c1b5e-2f8d-4e9a-8b1c-7d9a3f2b1e1b', value: 'DOCS_PENDING', label: 'Docs Pending', color: 'yellow', position: 1 },
        { id: '4a7c1b5e-2f8d-4e9a-8b1c-7d9a3f2b1e1c', value: 'DOCS_SUBMITTED', label: 'Docs Submitted', color: 'blue', position: 2 },
        { id: '4a7c1b5e-2f8d-4e9a-8b1c-7d9a3f2b1e1d', value: 'UNDER_SURVEY', label: 'Under Survey', color: 'orange', position: 3 },
        { id: '4a7c1b5e-2f8d-4e9a-8b1c-7d9a3f2b1e1e', value: 'UNDER_ASSESSMENT', label: 'Under Assessment', color: 'purple', position: 4 },
        { id: '4a7c1b5e-2f8d-4e9a-8b1c-7d9a3f2b1e1f', value: 'APPROVED', label: 'Approved', color: 'green', position: 5 },
        { id: '4a7c1b5e-2f8d-4e9a-8b1c-7d9a3f2b1e20', value: 'REJECTED', label: 'Rejected', color: 'red', position: 6 },
        { id: '4a7c1b5e-2f8d-4e9a-8b1c-7d9a3f2b1e21', value: 'SETTLED', label: 'Settled', color: 'sky', position: 7 },
        { id: '4a7c1b5e-2f8d-4e9a-8b1c-7d9a3f2b1e22', value: 'APPEAL', label: 'Appeal', color: 'orange', position: 8 },
      ]
    },
    {
      universalIdentifier: '4a7c1b5e-2f8d-4e9a-8b1c-7d9a3f2b1e12',
      type: FieldType.TEXT,
      name: 'rejectionReason',
      label: 'Rejection Reason',
      description: 'Rejection Reason',
      icon: 'IconTextCaption',
    },
    {
      universalIdentifier: '4a7c1b5e-2f8d-4e9a-8b1c-7d9a3f2b1e13',
      type: FieldType.RAW_JSON,
      name: 'requiredDocuments',
      label: 'Required Documents',
      description: 'Required Documents',
      icon: 'IconCode',
    },
    {
      universalIdentifier: '4a7c1b5e-2f8d-4e9a-8b1c-7d9a3f2b1e14',
      type: FieldType.RAW_JSON,
      name: 'surveyorDetails',
      label: 'Surveyor Details',
      description: 'Surveyor Details',
      icon: 'IconCode',
    },
    {
      universalIdentifier: '4a7c1b5e-2f8d-4e9a-8b1c-7d9a3f2b1e15',
      type: FieldType.RAW_JSON,
      name: 'tpaDetails',
      label: 'TPA Details',
      description: 'TPA Details',
      icon: 'IconCode',
    },
    {
      universalIdentifier: '4a7c1b5e-2f8d-4e9a-8b1c-7d9a3f2b1e16',
      type: FieldType.RAW_JSON,
      name: 'hospitalDetails',
      label: 'Hospital Details',
      description: 'Hospital Details',
      icon: 'IconCode',
    },
    {
      universalIdentifier: '4a7c1b5e-2f8d-4e9a-8b1c-7d9a3f2b1e17',
      type: FieldType.NUMBER,
      name: 'tatDays',
      label: 'TAT Days',
      description: 'TAT Days',
      icon: 'IconNumber',
    },
    {
      universalIdentifier: '4a7c1b5e-2f8d-4e9a-8b1c-7d9a3f2b1e18',
      type: FieldType.DATE_TIME,
      name: 'settlementDate',
      label: 'Settlement Date',
      description: 'Settlement Date',
      icon: 'IconCalendarEvent',
    },
    {
      universalIdentifier: '4a7c1b5e-2f8d-4e9a-8b1c-7d9a3f2b1e19',
      type: FieldType.FILES,
      name: 'documents',
      label: 'Documents',
      description: 'Documents',
      icon: 'IconFiles',
      universalSettings: { maxNumberOfValues: 10 },
    },
    {
      universalIdentifier: '4a7c1b5e-2f8d-4e9a-8b1c-7d9a3f2b1e1a',
      type: FieldType.RICH_TEXT,
      name: 'notes',
      label: 'Notes',
      description: 'Notes',
      icon: 'IconTextCaption',
    }
  ]
});
